#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_guidot = env_modules.Clone()

env_guidot.add_source_files(env.modules_sources, "*.cpp")
env_guidot.add_source_files(env.modules_sources, "widgets/*.cpp")
